### ISSUE TITLE
Install failed curb 0.9.6 on macOS Catalina

### ISSUE THREAD

**Issue by ShawnBaek** [taf2/curb#391] opened 2019-08-28 12:43 UTC
I got an error

How can I solve this problem?

```bash
curb_errors.c:337:10: error: duplicate case value: 'CURLE_PEER_FAILED_VERIFICATION' and 'CURLE_SSL_CACERT' both equal '60'
    case CURLE_SSL_CACERT:              /* 60 - problem with the CA cert (path?) */
         ^
curb_errors.c:310:10: note: previous case defined here
    case CURLE_SSL_PEER_CERTIFICATE:    /* 51 - peer's certificate wasn't ok */
         ^
/Users/user/Applications/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/curl/curl.h:628:36: note: expanded from macro 'CURLE_SSL_PEER_CERTIFICATE'
#define CURLE_SSL_PEER_CERTIFICATE CURLE_PEER_FAILED_VERIFICATION
                                   ^
1 error generated.
make: *** [curb_errors.o] Error 1

make failed, exit code 2
```

**Comment by rnhurt** [comment] 2019-10-03 20:27
I have this same issue trying to install on macOS Mojave.  😦

**Comment by tornglintaffychen** [comment] 2019-10-09 16:39
Same issue, couldn't find a way to solve this.

**Comment by aafaq-hassan-confiz** [comment] 2019-10-14 06:58
I have the same issue with curb 0.8.8 on macOS Catalina

**Comment by Nikhil-Wagh** [comment] 2019-10-21 12:24
SAME.

**Comment by Andre113** [comment] 2019-10-22 15:03
I managed to solve it by removing my Gemfile.lock:
`rm -rf Gemfile.lock`

And them running `bundle install`.

**Comment by jtswartz** [comment] 2019-10-25 17:52
@Andre113 thanks but that does not work for this issue. I'm getting:

`'CURLE_PEER_FAILED_VERIFICATION' and 'CURLE_SSL_CACERT' both equal '60'`

**Comment by runn-vermel** [comment] 2019-11-04 23:14
> @Andre113 thanks but that does not work for this issue. I'm getting:
> 
> `curb_errors.c:324:10: error: duplicate case value: 'CURLE_PEER_FAILED_VERIFICATION' and 'CURLE_SSL_CACERT' both equal '60'`

Same, I'm on Catalina.

**Comment by MarHelen** [comment] 2019-11-08 23:51
Fixed for my by replacing OpenSSL with LibreSSl

**Comment by taf2** [comment] 2019-11-18 12:07
Okay i can replicate this issue with a very simple example:

```c
  #include <curl/curl.h>
  int main(int argc) {
    switch(argc) {
    case CURLE_SSL_CACERT:
      break;
    case CURLE_SSL_PEER_CERTIFICATE:
      break;
    }
    return 0;
  }
```

We could convert this into a test in extconf.rb

```ruby
test_for("broken_ssl_curl", "CURLE_SSL_NOT_BROKEN_PEER_CACERT", %{
  #include <curl/curl.h>
  int main(int argc) {
    switch(argc) {
    case CURLE_SSL_CACERT:
      break;
    case CURLE_SSL_PEER_CERTIFICATE:
      break;
    }
    return 0;
  }
})
```
However we already addressed this issue:

see:

```c
#if LIBCURL_VERSION_NUM >= 0x073e00
    case CURLE_PEER_FAILED_VERIFICATION:              /* 60 - problem with the CA cert (path?) */
      exclz = eCurlErrSSLPeerCertificate;
#else
    case CURLE_SSL_CACERT:              /* 60 - problem with the CA cert (path?) */
      exclz = eCurlErrSSLCACertificate;
#endif
```

in ext/curb_errors.c

This is fixed in the latest version of curb.

 See:  aa23bf67
```
    from CHANGES:
    ssl: deprecate CURLE_SSL_CACERT in favour of a unified error code
    Long live CURLE_PEER_FAILED_VERIFICATION
```

**Closed by taf2** 2019-11-18 12:07 UTC

**Comment by andrecgro** [comment] 2019-11-20 22:36
So, as the problem was solved just now, we do not have an option for macOS Catalina users who uses old versions of curl (0.8.8), do we ?

**Comment by sunil-lulla** [comment] 2020-02-11 13:21
Any solutions on this one, for the version 0.8.8 macOS Catalina?

**Comment by luke-hill** [comment] 2020-02-11 15:15
The issue is fixed in the latest master. If you're on 0.8.8 I'd suggest upgrading. Maybe make a checkpoint to upgrade to 0.9.3 then furthermore?

**Comment by flavioalves** [comment] 2020-05-14 15:57
Same issue on Catalina 10.15.4 and ruby 2.3.6p384.

`
curb_errors.c:324:10: error: duplicate case value: 'CURLE_PEER_FAILED_VERIFICATION' and 'CURLE_SSL_CACERT' both equal '60'
    case CURLE_SSL_CACERT:  
`

**Comment by taf2** [comment] 2020-05-14 16:36
So... upgrade to a version of curb that has a corrected pre-processor line?

**Comment by jonbarlo** [comment] 2021-01-23 19:32
This seems to be working
    - `brew install rbenv/tap/openssl@1.0`
    - `gem install bundler -v '1.9.2'`
    - `RUBY_CONFIGURE_OPTS="--with-openssl-dir=/usr/local/opt/openssl@1.0" CFLAGS="-Wno-error=implicit-function-declaration" rbenv install 2.1.9`
    - `brew install v8@3.15`
    - `gem install libv8 -v 3.16.14.3 -- --with-system-v8`
    - `gem install therubyracer -v '0.12.1' -- --with-v8-dir=/usr/local/opt/v8@3.15`
    - `bundle install`

Ruby < 2.5 + Catalina + XCode12

**Comment by leobagua** [comment] 2021-08-02 22:35
Found this issue today while trying to run `gem install curb -v '0.9.3'`. Unfortunately, upgrading `curb` version was not an option for me. So, I've built `curl -v 7.54.0` from source in a temp folder and installed the gem using this version of curl.

1. **Download `curl 7.54.0` to any folder**
```bash
cd
wget https://curl.se/download/curl-7.54.0.tar.gz
tar xvfz curl-7.54.0.tar.gz
cd curl-7.54.0
./configure --prefix=/Users/Your User/curl-fix/7_54_0 # Remember this path
make CFLAGS=-Wno-error
make install CFLAGS=-Wno-error
```
>Now curl 7.54 is installed at /Users/Your User/curl-fix/7_54_0

2. **Export the paths for `curl 7.54.0`**
```bash
export PATH="/Users/Your User/curl-fix/7_54_0/bin:$PATH"
export LDFLAGS="-L/Users/Your User/curl-fix/7_54_0/lib"
export CPPFLAGS="-I/Users/Your User/curl-fix/7_54_0/include"
export PKG_CONFIG_PATH="/Users/Your User/curl-fix/7_54_0/lib/pkgconfig"
```

3. **Make sure that your `curl --version` is `curl 7.54.0`**
4. **Install curb**
```bash
gem install curb -v X.X.X
```
5. Working on `macOS Big Sur 11.5.1`

**Comment by taf2** [comment] 2021-08-02 23:06
@leobagua - cool, can i ask why you can't upgrade curb?

**Comment by leobagua** [comment] 2021-08-02 23:17
@taf2 We have some dependencies between old ruby-clients in our tech stack. One of our old ruby clients is using `curb 0.9.3`. For the sake of compatibility, we are unable to bump the `curb` version in this specific ruby-client.

**Comment by taf2** [comment] 2021-08-02 23:39
@leobagua sorry to hear that... I am pretty certain that there have been zero breaking changes since 0.9.3... perhaps you can bump the version number if you find a bug would love to know what regression because pretty sure we've only added either new curl interfaces or fixed existing bugs since 0.9.3... might want to give it an upgrade

**Comment by leobagua** [comment] 2021-08-03 00:13
@taf2 nice to hear that. I'll propose the changes to the team

**Comment by clinton-haley** [comment] 2021-08-19 15:14
Thank you @leobagua.  I followed your instruction but installed curl v 7.58.0 and curb v 0.8.8 and it worked 100%.

**Comment by sripriyesha** [comment] 2021-12-08 07:47
Installing the latest version of curb (0.9.11 at the time i'm writing) solved it for me

**Comment by yagobatista** [comment] 2025-01-17 14:05
this worked for me
```
gem install curb -v '0.9.10' -- --with-cflags="-Wno-error=incompatible-function-pointer-types"   
```
